"""Order book, work, people and cases.

The order book is the one that matters most on a demonstration, because it is the
question a distribution business actually loses sleep over: we have promised these
goods, can we deliver them. Undelivered value against free-to-sell stock is the
comparison, and both sides of it are now facts.
"""

from command_center.kpi.registry import Kpi, register

OPEN_ORDER = {"is_open": 1}
OPEN_TASK = {"is_open": 1}
OPEN_CASE = {"is_open": 1}
ACTIVE = {"is_active": 1}

register(
    # ---------------------------------------------------------------- order book
    Kpi(
        key="order_book",
        label="Promised, not delivered",
        fact="fact_sales_order",
        measure="undelivered_value",
        unit="currency",
        direction="neutral",
        filters=OPEN_ORDER,
        note="across {order_book_count} open orders",
        drill_filters=OPEN_ORDER,
        as_of_basis="data_horizon",
        components=("order_book_late", "order_book_on_time"),
    ),
    Kpi(
        key="order_book_count",
        label="Open orders",
        fact="fact_sales_order",
        measure="*",
        agg="count",
        unit="count",
        filters=OPEN_ORDER,
        note="worth {order_book} still to deliver",
        drill_filters=OPEN_ORDER,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="order_book_late",
        label="Past the promised date",
        fact="fact_sales_order",
        measure="undelivered_value",
        unit="currency",
        direction="higher_is_worse",
        filters={**OPEN_ORDER,
                 "lateness_bucket": ["in", ["0-30", "31-60", "61-90", "90+"]]},
        note="{order_book_late_share} of the order book",
        drill_filters={**OPEN_ORDER,
                       "lateness_bucket": ["in", ["0-30", "31-60", "61-90", "90+"]]},
        as_of_basis="data_horizon",
        subset_of="everything promised and not delivered",
        share_of="order_book",
    ),
    Kpi(
        key="order_book_on_time",
        label="Still within the promise",
        fact="fact_sales_order",
        measure="undelivered_value",
        unit="currency",
        filters={**OPEN_ORDER,
                 "lateness_bucket": ["in", ["Not yet due", "No date set"]]},
        note="{order_book_on_time_share} of the order book",
        drill_filters={**OPEN_ORDER,
                       "lateness_bucket": ["in", ["Not yet due", "No date set"]]},
        as_of_basis="data_horizon",
        subset_of="everything promised and not delivered",
        share_of="order_book",
    ),
    Kpi(
        key="order_book_late_pct",
        label="Order book past its promise",
        fact="fact_sales_order",
        measure="*",
        agg="ratio",
        numerator="order_book_late",
        denominator="order_book",
        unit="percent",
        direction="higher_is_worse",
        note="of {order_book} still to deliver",
        as_of_basis="data_horizon",
        subset_of="everything promised and not delivered",
    ),
    Kpi(
        key="order_unbilled",
        label="Delivered but not invoiced",
        fact="fact_sales_order",
        measure="unbilled_value",
        unit="currency",
        direction="higher_is_worse",
        filters=OPEN_ORDER,
        note="revenue earned and not yet billed",
        drill_filters=OPEN_ORDER,
        as_of_basis="data_horizon",
    ),

    # ---------------------------------------------------------------------- work
    Kpi(
        key="tasks_open",
        label="Work in flight",
        fact="fact_task",
        measure="*",
        agg="count",
        unit="count",
        direction="neutral",
        filters=OPEN_TASK,
        note="{tasks_overdue} of them past due",
        drill_filters=OPEN_TASK,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="tasks_overdue",
        label="Past due",
        fact="fact_task",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters={**OPEN_TASK,
                 "lateness_bucket": ["in", ["0-30", "31-60", "61-90", "90+"]]},
        note="{tasks_overdue_share} of work in flight",
        drill_filters={**OPEN_TASK,
                       "lateness_bucket": ["in", ["0-30", "31-60", "61-90", "90+"]]},
        as_of_basis="data_horizon",
        subset_of="all work in flight",
        share_of="tasks_open",
    ),
    Kpi(
        key="tasks_unowned",
        label="Nobody assigned",
        fact="fact_task",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters={**OPEN_TASK, "is_assigned": 0},
        # The finding, not a gap in the data: work with no owner is work nobody has
        # agreed to do, and it is the single most actionable thing on this screen.
        note="open work with no owner",
        drill_filters={**OPEN_TASK, "is_assigned": 0},
        as_of_basis="data_horizon",
    ),

    # -------------------------------------------------------------------- people
    Kpi(
        key="headcount",
        label="People employed",
        fact="fact_person",
        measure="*",
        agg="count",
        unit="count",
        direction="neutral",
        filters=ACTIVE,
        note="across {departments} departments",
        drill_filters=ACTIVE,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="departments",
        label="Departments",
        fact="fact_person",
        measure="*",
        agg="count_distinct",
        distinct_on="department",
        unit="count",
        direction="neutral",
        filters=ACTIVE,
        note="with someone active in them",
        drill_filters=ACTIVE,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="people_without_login",
        label="No ERPNext login",
        fact="fact_person",
        measure="*",
        agg="count",
        unit="count",
        direction="neutral",
        filters={**ACTIVE, "has_user": 0},
        note="employed, but cannot sign in",
        drill_filters={**ACTIVE, "has_user": 0},
        as_of_basis="data_horizon",
    ),

    # --------------------------------------------------------------------- cases
    Kpi(
        key="cases_open",
        label="Open complaints",
        fact="fact_case",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters=OPEN_CASE,
        note="{cases_unowned} with nobody assigned",
        drill_filters=OPEN_CASE,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="cases_unowned",
        label="Complaints with no owner",
        fact="fact_case",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters={**OPEN_CASE, "is_assigned": 0},
        note="nobody has picked these up",
        drill_filters={**OPEN_CASE, "is_assigned": 0},
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="cases_over_30",
        label="Waiting over a month",
        fact="fact_case",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters={**OPEN_CASE, "wait_bucket": ["in", ["31-60", "61-90", "90+"]]},
        note="{cases_over_30_share} of open complaints",
        drill_filters={**OPEN_CASE, "wait_bucket": ["in", ["31-60", "61-90", "90+"]]},
        as_of_basis="data_horizon",
        subset_of="all open complaints",
        share_of="cases_open",
    ),
)
