"""Sales and receivables KPIs.

Every figure here reconciles to the source: 9,177,568.91 across 806 unpaid
invoices, of which 6,777,143 is beyond three months, measured as at the latest
date the data covers.
"""

from command_center.kpi.registry import Kpi, register

UNPAID = {"outstanding_amount": [">", 0], "src_docstatus": 1}
SUBMITTED = {"src_docstatus": 1}

register(
    Kpi(
        key="ar_total",
        label="Owed to us",
        fact="fact_sales_invoice",
        measure="outstanding_amount",
        unit="currency",
        direction="higher_is_worse",
        filters=UNPAID,
        note="{ar_count} unpaid invoices",
        drill_filters=UNPAID,
        as_of_basis="data_horizon",
        components=("ar_over_90", "ar_inside_90"),
    ),
    Kpi(
        key="ar_count",
        label="Unpaid invoices",
        fact="fact_sales_invoice",
        measure="*",
        agg="count",
        unit="count",
        direction="neutral",
        filters=UNPAID,
        note="worth {ar_total}",
        drill_filters=UNPAID,
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="ar_over_90",
        label="Over three months",
        fact="fact_sales_invoice",
        measure="outstanding_amount",
        unit="currency",
        direction="higher_is_worse",
        filters={**UNPAID, "ageing_bucket": "90+"},
        note="{ar_over_90_share} of the balance",
        drill_filters={**UNPAID, "ageing_bucket": "90+"},
        as_of_basis="data_horizon",
        subset_of="everything owed",
        share_of="ar_total",
    ),
    Kpi(
        key="ar_inside_90",
        label="Still inside 90 days",
        fact="fact_sales_invoice",
        measure="outstanding_amount",
        unit="currency",
        direction="neutral",
        filters={**UNPAID,
                 "ageing_bucket": ["in", ["Not yet due", "0-30", "31-60", "61-90"]]},
        note="{ar_inside_90_share} of the balance",
        drill_filters={**UNPAID,
                       "ageing_bucket": ["in", ["Not yet due", "0-30", "31-60", "61-90"]]},
        as_of_basis="data_horizon",
        subset_of="everything owed",
        share_of="ar_total",
    ),
    Kpi(
        key="revenue_invoiced",
        label="Invoiced revenue",
        fact="fact_sales_invoice_line",
        measure="base_net_amount",
        unit="currency",
        direction="higher_is_better",
        filters=SUBMITTED,
        note="across every submitted invoice line",
        drill_filters=SUBMITTED,
        as_of_basis="data_horizon",
        components=("revenue_costed", "revenue_uncosted"),
    ),
    Kpi(
        key="revenue_costed",
        label="Revenue with a cost behind it",
        fact="fact_sales_invoice_line",
        measure="base_net_amount",
        unit="currency",
        direction="neutral",
        filters={**SUBMITTED, "has_cost": 1},
        note="{revenue_costed_share} of invoiced revenue",
        drill_filters={**SUBMITTED, "has_cost": 1},
        as_of_basis="data_horizon",
        subset_of="all invoiced revenue",
        share_of="revenue_invoiced",
    ),
    Kpi(
        key="revenue_uncosted",
        label="Revenue with no cost behind it",
        fact="fact_sales_invoice_line",
        measure="base_net_amount",
        unit="currency",
        direction="higher_is_worse",
        # The margin on this revenue is unknown, not zero. It is small here, but it
        # is the amount by which a margin percentage taken over all lines would be
        # wrong -- which is why margin_pct divides by revenue_costed instead.
        filters={**SUBMITTED, "has_cost": 0},
        note="sold with no valuation recorded",
        drill_filters={**SUBMITTED, "has_cost": 0},
        as_of_basis="data_horizon",
        subset_of="all invoiced revenue",
        share_of="revenue_invoiced",
    ),
    Kpi(
        key="margin_known_cost",
        label="Margin, where cost is known",
        fact="fact_sales_invoice_line",
        measure="base_margin_amount",
        unit="currency",
        direction="higher_is_better",
        filters={**SUBMITTED, "has_cost": 1},
        # Not a caveat anyone has to remember to add: lines with no valuation are
        # excluded by the filter, and the subset is declared so the figure cannot
        # be read as total margin.
        note="{margin_excluded_lines} lines have no cost recorded and are excluded",
        drill_filters={**SUBMITTED, "has_cost": 1},
        as_of_basis="data_horizon",
        subset_of="invoice lines that carry a valuation",
    ),
    Kpi(
        key="margin_excluded_lines",
        label="Lines with no cost",
        fact="fact_sales_invoice_line",
        measure="*",
        agg="count",
        unit="count",
        direction="higher_is_worse",
        filters={**SUBMITTED, "has_cost": 0},
        note="reported as margin only if the flag is ignored",
        drill_filters={**SUBMITTED, "has_cost": 0},
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="cash_applied",
        label="Cash applied",
        fact="fact_payment_allocation",
        measure="allocated_amount",
        unit="currency",
        direction="higher_is_better",
        filters={},
        note="matched to a document",
        drill_filters={},
        as_of_basis="data_horizon",
    ),
    Kpi(
        key="margin_pct",
        label="Margin",
        fact="fact_sales_invoice_line",
        measure="*",
        agg="ratio",
        numerator="margin_known_cost",
        denominator="revenue_costed",
        unit="percent",
        direction="higher_is_better",
        note="on {revenue_costed}, the revenue whose cost is known",
        as_of_basis="data_horizon",
        subset_of="invoice lines that carry a valuation",
    ),
    Kpi(
        key="ar_over_90_pct",
        label="Share beyond three months",
        fact="fact_sales_invoice",
        measure="*",
        agg="ratio",
        numerator="ar_over_90",
        denominator="ar_total",
        unit="percent",
        direction="higher_is_worse",
        note="of {ar_total} owed",
        as_of_basis="data_horizon",
        subset_of="everything owed",
    ),
)
