# -*- coding: utf-8 -*-
# Every clickable card -> where the number comes from, how it is worked out, what is behind it.
EX={
 "rev":("Money coming in","Confirmed customer orders, added up by the month they were placed.",
  [("Where it is kept","ERPNext, under customer orders"),
   ("What counts","Only confirmed orders. Anything still a draft is left out."),
   ("How it is worked out","Every order's value, grouped by the month it was placed"),
   ("What it excludes","Cancelled orders, and the 88 invoices never issued"),
   ("How fresh","Read this morning at 06:58 from a copy taken to 19 August 2025")],
  "Eleven months are shown. June 2025 was the strongest at GHS 3.19M; November 2024 the weakest at GHS 260,486."),
 "ar":("Money owed to us","What customers have been invoiced and have not yet paid.",
  [("Where it is kept","ERPNext, on each customer's account"),
   ("What counts","Confirmed invoices with an amount still outstanding"),
   ("How it is worked out","Outstanding amount per invoice, grouped by customer and by how old it is"),
   ("How the ages are set","From each invoice's due date to today"),
   ("Checked against","The customer account balances in ERPNext — they agree exactly")],
  "GHS 9,177,569 across 806 unpaid invoices. GHS 6,777,143 of it \u2014 74% \u2014 has been outstanding more than three months, measured as at 19 August 2025, the last date the data covers. The ten largest customers hold GHS 4,592,482, exactly half."),
 "openorders":("Orders taken but not despatched","Orders the customer has confirmed where the goods have not left.",
  [("Where it is kept","ERPNext, under customer orders"),
   ("What counts","Confirmed orders not yet fully despatched"),
   ("How it is worked out","How much of each order has been despatched and invoiced"),
   ("Why an order can be stuck","No stock · nothing ordered from a supplier · nothing despatched · not invoiced · installation outstanding · not paid")],
  "Four orders, GHS 84,950 between them. The Ejura order alone is GHS 65,100."),
 "drafts":("Invoices written but never issued","Invoices created and left unfinished.",
  [("Where it is kept","ERPNext, under customer invoices"),
   ("What counts","Invoices that were never confirmed"),
   ("Why they are excluded","An unissued invoice is not money owed. Counting it would overstate the position."),
   ("Why they still matter","Somebody did work and started to bill for it. Nobody finished.")],
  "88 of them. They appear in no total on this platform, by design — and nobody is chasing them either."),
 "funnel":("From enquiry to order","How work turns from an enquiry into a confirmed order.",
  [("Where it is kept","ERPNext — enquiries, opportunities, quotations and orders"),
   ("What it counts","How many reach each stage, and what they are worth"),
   ("What it shows here","17 enquiries · 0 opportunities · 122 quotations · 1,436 orders")],
  "Most orders never begin as a quotation. Conversion cannot be measured properly until quotations are used consistently — worth raising, because it is the one number that predicts next quarter."),
 "supp":("Where the money goes","Purchase orders totalled by supplier.",
  [("Where it is kept","ERPNext, under purchase orders"),
   ("What counts","Confirmed purchase orders"),
   ("How it is worked out","Order value totalled per supplier across the fourteen largest"),
   ("What to watch","How much depends on any single supplier")],
  "SICHUAN M.K.R is about 57% on its own. With CYNSEL INNOVATION it is roughly 95%. Both ship from abroad."),
 "lead":("How long suppliers take","Days between placing an order and the date the supplier promised.",
  [("Where it is kept","ERPNext, under purchase orders"),
   ("How it is worked out","Promised date minus order date"),
   ("A warning","Two of the fourteen largest have the same date for both, meaning no promised date was ever entered. Those show as zero rather than being hidden.")],
  "The longest is 184 days — ordered in December, promised for the end of June. That is half a year of cash tied up before anything arrives."),
 "spend":("Spend on buying","The value of purchase orders placed.",
  [("Where it is kept","ERPNext, under purchase orders"),("What counts","Confirmed orders"),
   ("Covers","The fourteen largest, GHS 8.43M between them")],
  "299 purchase orders exist in total. The fourteen shown here are the largest by value."),
 "po":("Purchase orders","Every order placed with a supplier.",
  [("Where it is kept","ERPNext, under purchase orders"),("How many","299 in total")],
  "Only two of the fourteen largest remain open."),
 "stockval":("Stock we hold","The value of goods on hand, by location.",
  [("Where it is kept","ERPNext, in the stock position for each product and location"),
   ("How it is worked out","Quantity held multiplied by its recorded cost, totalled by location"),
   ("Reconciles","704 records carry a value; they add to GHS 3,769,970 exactly")],
  "GHS 1,175,920 of that — about a third — is in a stock adjustment account rather than a warehouse."),
 "recon":("Stock outside any warehouse","Goods recorded in an adjustment account rather than a location.",
  [("Where it is kept","ERPNext, in the stock position"),
   ("What it is","An account used to correct counts, being used as a store"),
   ("Why it matters","Nothing can be sold or reserved from there"),
   ("What is in it","Two new haematology analysers, an anaesthesia machine, 15 hospital beds, 946 crutches")],
  "GHS 1,175,920 across the top 100 of 207 lines, so the real figure is higher."),
 "worst":("The worst single shortfall","The product with the largest gap between promised and held.",
  [("Where it is kept","ERPNext, in the stock position for each product and location"),
   ("How it is worked out","Quantity promised minus quantity actually held, ranked"),
   ("Why this one matters","288 promised for every one held, on an item sold every day")],
  "Syringe &amp; needle 5ml at Central Warehouse: 40,080 promised, 139 present."),
 "reserved":("Lines carrying a promise","Product-location records with stock committed to a customer.",
  [("Where it is kept","ERPNext, in the stock position"),
   ("How it is worked out","Any record with a quantity reserved against it"),
   ("The number that matters","How many of those actually have stock behind them")],
  "771 lines carry a promise. Only 280 &mdash; 36% &mdash; have any stock at all."),
 "nodate":("Orders with no delivery date","Purchase orders placed without a date the supplier agreed to.",
  [("Where it is kept","ERPNext, on each purchase order"),
   ("How it is spotted","The promised date is the same as the order date, or absent"),
   ("Why it matters","Nothing can be chased, because nothing can be late")],
  "Two orders worth GHS 977,077 together, both with the same supplier on the same day."),
 "disabled":("Accounts switched off","Logins blocked for people who have left.",
  [("Where it is kept","ERPNext, on each user account"),
   ("What blocking does","Prevents sign-in. It does not remove the roles."),
   ("What to watch","Re-enabling an account restores every role it had")],
  "Four accounts, all correctly blocked."),
 "conflicts":("One person, both sides","Accounts holding role combinations that defeat the approval chain.",
  [("Where it is kept","ERPNext, in the role assignments"),
   ("How it is spotted","Pairs of roles that should never sit together on one account"),
   ("What it is not","An accusation. It is a statement about what the permissions currently allow.")],
  "Three of thirteen active accounts."),
 "roles5":("Accounts holding five roles","People carrying five manager roles at once.",
  [("Where it is kept","ERPNext, in the role assignments"),
   ("Why it happens","Roles accumulate as people cover for others and are rarely taken away again")],
  "Three people, each spanning finance, stock, buying and HR."),
 "raise":("What would be raised today","Findings the platform would open on its first morning.",
  [("Where they come from","Control Health, which scores six questions every day"),
   ("What happens next","Each becomes a finding with an owner, a date and the evidence needed to close it")],
  "Six, all found in the records before anything was built."),
 "over":("Reserved but unavailable","Products committed to customers beyond what is physically there.",
  [("Where it is kept","ERPNext, in the stock position for each product and location"),
   ("How it is worked out","Quantity promised against quantity actually held"),
   ("What counts","Anywhere the promise exceeds what is there")],
  "491 of 2,375 product-location records. The worst is 40,080 syringes promised against 139 held."),
 "expiry":("Expiry","When stock goes out of date.",
  [("Where it would be kept","ERPNext, on each batch"),
   ("Why it is empty here","Expiry dates are not captured on goods-in in this copy"),
   ("Why it matters","For a medical supplier, expired stock is both a write-off and a safety matter")],
  "This is the panel that would matter most in service. It needs expiry dates recorded when goods arrive."),
 "jobs":("Engineering jobs","Installation and service work, run through Projects.",
  [("Where it is kept","ERPNext, under projects and their tasks"),
   ("What counts","Projects that are engineering work rather than office matters"),
   ("A warning","Staff departures and office admin are filed in the same list, so a straight count of projects would mislead")],
  "30 projects in total; 14 are open engineering work."),
 "late":("Jobs past their promised date","Work promised to a customer by a date that has passed.",
  [("Where it is kept","ERPNext, under projects"),
   ("How it is worked out","Promised completion date against today"),
   ("What it shows","Six jobs past their date, the oldest by 28 months")],
  "Three of them are for UBUNTU, all promised for 28 February 2025 and none started."),
 "unassigned":("Jobs with nobody assigned","Open work with no named owner.",
  [("Where it is kept","ERPNext, on each project and task"),
   ("How it is worked out","Open jobs with no person assigned")],
  "Eleven of fourteen open jobs. Work with no name against it does not get done."),
 "capacity":("Engineers on staff","People employed to do installation and service work.",
  [("Where it is kept","ERPNext, in the employee records"),
   ("How it is worked out","Active employees in engineering roles"),
   ("What it shows","Three, across Accra, Kumasi and head office — all titled sales engineers")],
  "Three engineers, fourteen open jobs, six of them past their promised date. That is a capacity problem, not a diligence problem."),
 "jobcost":("Cost against a job","What an installation actually cost to carry out.",
  [("Where it would come from","Parts issued, hours booked, travel claimed, all tied to the job"),
   ("Why it is empty here","No job in this copy carries a cost"),
   ("Why it matters","Without it, nobody knows whether installations make money or lose it")],
  "This is the single biggest gap in the engineering picture."),
 "ubuntu":("UBUNTU — both sides","Everything about one customer in one place.",
  [("Where it is kept","ERPNext — their customer account and three projects"),
   ("Why it is shown together","The money and the work are held in different parts of ERPNext and nothing connects them")],
  "They owe GHS 636,675 over three months old. We owe them three installations promised nineteen months ago."),
 "cases":("Customer complaints","Problems customers have raised with us.",
  [("Where it is kept","ERPNext, under customer issues"),
   ("What counts","Cases not yet closed"),
   ("Please note","All eleven were created by us for this demonstration. Gigmann's copy held none.")],
  "Six open, four of them urgent, two involving equipment a hospital cannot use."),
 "sla":("How long customers wait","Time from raising a complaint to it being resolved.",
  [("Where it is kept","ERPNext, on each case"),
   ("How it is worked out","From when the case was raised to now, for anything still open"),
   ("Against what","The response time promised for that kind of case")],
  "Six cases are past the promised time, the longest by 25 days."),
 "down":("Equipment a customer cannot use","Complaints where a machine is out of service.",
  [("Where it is kept","ERPNext, on each case"),("Why separate","A hospital with an X-ray out of service is a different problem from a billing query")],
  "Two: an X-ray generator and an autoclave."),
 "crossover":("Complaining and owing","Customers on both lists at once.",
  [("How it is worked out","Open complaints matched against outstanding balances")],
  "Three of six open complaints are from customers who owe money. Worth knowing before anyone rings them."),
 "causes":("What they complain about","Complaints grouped by what went wrong.",
  [("Where it is kept","ERPNext, on each case"),("How it is grouped","By the nature of the problem")],
  "Equipment faults are the largest group. With a full year of history this becomes a reliability picture per product."),
 "head":("Headcount","People on the books.",
  [("Where it is kept","ERPNext, in the employee records"),
   ("What counts","Everyone on record, whether active, inactive or departed"),
   ("What you can see","Numbers by department and branch. Names, pay and conduct records are hidden unless you hold HR.")],
  "35 on the books: 24 active, 3 inactive, 8 departed."),
 "turnover":("People leaving","Who has left, when, and how long they stayed.",
  [("Where it is kept","ERPNext, in the employee records"),
   ("How it is worked out","Departed against total on the books, with joining and leaving dates"),
   ("Why tenure matters more than the count","A quarter leaving is one story if they stayed years, another if they stayed months"),
   ("Who can see the names","HR and the chief executive only")],
  "8 of 35 have left — close to a quarter. <b>Average tenure of those who left is seven months</b>, and four of the eight lasted under six."),
 "depts":("Departments","How people are grouped.",
  [("Where it is kept","ERPNext, on each employee record"),
   ("A warning","Several departments are recorded under two different spellings, so counts by department cannot yet be trusted")],
  "Ten departments listed, but at least three pairs look like the same department typed twice."),
 "payroll":("Payroll","Whether pay has been run, and whether anything moved unusually.",
  [("Where it is kept","ERPNext, in the payroll records"),
   ("What this platform does","Shows the status and flags unusual movement"),
   ("What it never does","Calculate pay, change pay, or show individual salaries outside HR")],
  "This platform reads payroll. It cannot write to it, and neither can the assistant."),
 "fresh":("How fresh the figures are","When the data behind these screens was last read.",
  [("How it works","Changes are read from ERPNext every few minutes in service"),
   ("This copy","Was taken to 19 August 2025 and is deliberately behind")],
  "Every screen carries this. A number that is old says so rather than passing as today's."),
 "access":("Who can get in","Everyone with an account on this platform.",
  [("How access works","Granted per role and per business. Nobody gets access by default."),
   ("Who is excluded","Everyone outside management. There is no general staff login.")],
  "Seven accounts. Work handed out reaches staff in ERPNext, where they already work."),
 "bank":("Bank checks","Whether bank accounts have been checked against the books.",
  [("Where it is kept","ERPNext, in the banking records"),
   ("Why it matters","Every cash figure on this platform depends on it")],
  "Status not confirmed in this copy. It is the first thing to establish."),
 "workingcap":("Money the business cannot use","Cash tied up where it cannot be spent.",
  [("How it is worked out","Debts over three months old, plus stock outside any warehouse, plus orders taken but not despatched"),
   ("Why together","These usually live in three different reports, so nobody sees the total")],
  "GHS 5.77M against a stock holding of GHS 3.77M."),
 "find":("Audit findings","Problems recorded, owned and tracked to closure.",
  [("Where it would be kept","This platform — ERPNext has nowhere to record it"),
   ("What a finding carries","What was found, the evidence, how serious, who owns it, and what they will do")],
  "Nothing recorded yet. Six would be raised on the first morning, all from Control Health."),
 "score":("Control health score","Whether the records the business runs on can be trusted.",
  [("How it is worked out","Six questions scored and combined"),
   ("What moves it","People fixing things")],
  "44 out of 100. Two of the six questions are failing."),
 "stuck":("Raised but never submitted",
  "Purchase orders that were created and then left, without ever entering the approval process.",
  [("Where it is kept","ERPNext, on each purchase order"),
   ("How it is worked out","Orders whose approval stage is still Draft"),
   ("Why it matters","They commit nothing and warn nobody. Stock is not ordered and no one is chasing."),
   ("How to stop it","A weekly list of anything raised and not submitted within seven days")],
  "Eleven orders worth GHS 903,632. Five are over GHS 50,000 and the oldest dates from July 2024."),
 "selfapp":("Approvals completed by whoever raised them",
  "Where one account moved a document through every approval stage itself.",
  [("Where it is kept","ERPNext change history \u2014 each stage change is recorded"),
   ("How it is spotted","The account that raised the document is the same one that moved every stage"),
   ("Why it happens","Role stacking. Three active accounts hold five manager roles each."),
   ("What it is not","Evidence of wrongdoing. It is evidence that the control cannot currently work as designed.")],
  "Two clear cases in the records examined: a purchase order through four stages in fourteen seconds, and a payment through two in five."),
 "cancelled":("Withdrawn after being raised",
  "Documents taken back after they were created.",
  [("Where it is kept","ERPNext, on the document"),
   ("Why it is worth watching","Occasional cancellations are normal. Large or repeated ones near a period end are worth a look.")],
  "Three of the largest: GHS 1,283,800, GHS 490,000 and GHS 469,264."),
 "trail":("The record of every change",
  "Kept by ERPNext for its own records, extended by this platform for everything else.",
  [("How far back","5 February 2024 \u2014 about nineteen months"),
   ("How many","91,133 changes, of which 46,975 are business records"),
   ("How granular","Every individual change, with the field, the value before and after, who and when"),
   ("What cannot happen","No entry can be edited or deleted, including by an administrator"),
   ("How it is protected","Each entry carries a fingerprint of the one before it, so a removal breaks the chain")],
  "An invoice amended four times appears four times. Nothing is summarised away."),
 "identity":("Who you are, and what you may see",
  "Worked out from ERPNext every time, never typed into this platform.",
  [("Who does what","The employee records — designation, department, branch"),
   ("Who leads","The reporting tree. Whoever has nobody above them is the chief executive."),
   ("What they may do","The roles on their linked ERPNext account"),
   ("How access follows","A published rule, editable by an administrator, shown on this screen"),
   ("Several people, same access","Normal and supported — access attaches to people, not to a single seat")],
  "Only 5 of 35 employee records are linked to a login today, so most people are known to the platform but cannot yet sign in."),
 "discount":("Discounts outside policy","Prices given away beyond what is allowed.",
  [("Where it would be kept","ERPNext, on quotations and orders"),
   ("Why it is empty here","No discount in this copy exceeds a threshold")],
  "The panel stays so the finished screen is the shape you see now."),
}
